server:
  port: 8282
spring:
  datasource:
    url:
    username:
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
application:
  minio-storage:
    application: images
    host: 'http://127.0.0.1:9000'
    username: minioadmin
    password: minioadmin