server:
  port: 8282
spring:
  datasource:
    url:
    username:
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    minioStorage:
          application: test-app
          host: 'http://127.0.0.1:9090'
          username: minioadmin
          password: minioadmin